language: node_js
node_js:
  - 'stable'
cache: npm
install:
  - npm install
services:
  - postgresql
notifications:
  email: false
before_script:
  - psql -c 'create database travis_test_db;' -U postgres
script:
  - npm test
after_success:
  - npm run coverage
